---

### This Playbook does initial setup to all 3 servers and limits connectivity ###
- hosts: all
  become: yes
  become_method: sudo
 
  tasks:
    # Installs ifupdown for permanent change of the iptables after restart  
    - name: Install ifupdown
      apt:
        name: ifupdown
        update_cache: yes
    
    # Setting up iptables rules for the 3 servers (Some rules are spesific to certain servers)
    - name: Flush all iptables Rules
      command: iptables -F
    
    - name: Set Loop Back Rule
      iptables: chain=INPUT action=append in_interface=lo jump=ACCEPT comment='Accept all loop back traffic'

    - name: Set Established Connection Rule
      iptables: chain=INPUT ctstate='ESTABLISHED,RELATED' jump=ACCEPT comment='Let all established connection stay'

    - name: Set SSH Port 22 SSH Rule
      iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=22 comment='Accept all SSH traffic'

    - name: Set HTTP Port 80 HTTP Rule on Server A
      iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=80 comment='Accept all HTTP traffic'
      when: "'A' in group_names"
    
    - name: Set port 8080 to the iptables on Servers B and C
      iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=8080 comment='Accept 8080 traffic'
      when: "'B_C' in group_names"
      
    - name: Set HTTP Port 443 SSL Rule
      iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=443 comment='Accept all SSL traffic'

    - name: Set HTTP Port 3306 SSL Rule
      iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=3306 comment='Accept all MySQL traffic'

    - name: Drop Any Traffic Without Rule
      iptables: chain=INPUT jump=DROP comment='Drop traffic for rules that did not match'
    
    # Saves the iptables rules for ifupdown usage:
    - name: Save iptables rules
      command: sh -c "iptables-save > /etc/iptables.rules"
    
    # Copy "interface" script to the server to restore the iptables on startup
    - name: Copy to the machine the interface file and making the iptables change permanent
      copy: 
        src: /etc/network/interfaces
        dest: /etc/network/interfaces
    
    # Making sure the servers are accessible only through SSH, without username & password login
    - name: Limits to only SSH key login
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        owner: root
        group: root
        mode: '0644'
        backup: yes